["default"]
15_min = 8
hourly = 24
daily = 0
monthly = 0

["root_pool/home"]
15_min = 8
hourly = 24
daily = 14
monthly = 0

["root_pool/root"]
15_min = 8
hourly = 24
daily = 0
monthly = 0

["root_pool/nix"]
15_min = 4
hourly = 0
daily = 0
monthly = 0

["root_pool/var"]
15_min = 8
hourly = 24
daily = 30
monthly = 6

["storage/plex"]
15_min = 6
hourly = 2
daily = 1
monthly = 0

["media/plex"]
15_min = 6
hourly = 2
daily = 1
monthly = 0

["media/notes"]
15_min = 8
hourly = 24
daily = 30
monthly = 12

["media/docker"]
15_min = 3
hourly = 12
daily = 14
monthly = 2

["media/services"]
15_min = 3
hourly = 12
daily = 14
monthly = 2

["media/home_assistant"]
15_min = 3
hourly = 12
daily = 14
monthly = 2

["scratch/transmission"]
15_min = 0
hourly = 0
daily = 0
monthly = 0

["storage/transmission"]
15_min = 0
hourly = 0
daily = 0
monthly = 0

["storage/ollama"]
15_min = 0
hourly = 0
daily = 0
monthly = 0
