esphome:
  name: battery1
  friendly_name: battery1

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key

external_components:
  - source: github://syssi/esphome-jk-bms@main

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

ble_client:
  - mac_address: "C8:47:80:37:9D:DD"
    id: jk_ble1

jk_bms_ble:
  - ble_client_id: jk_ble1
    protocol_version: JK02_32S
    throttle: 1s
    id: jk_bms1

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "JK1 retrieve settings"
    retrieve_device_info:
      name: "JK1 retrieve device info"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: jk_bms1
    total_voltage:
      name: "JK1 Total Voltage"
    state_of_charge:
      name: "JK1 SoC"
    charging_power:
      name: "JK1 charging power"
    discharging_power:
      name: "JK1 discharging power"
    temperature_sensor_1:
      name: "JK1 Temp 1"
    temperature_sensor_2:
      name: "JK1 Temp 2"
    balancing:
      name: "JK1 balancing"
    total_runtime:
      name: "JK1 total runtime"
    balancing_current:
      name: "JK1 balancing current"
    delta_cell_voltage:
      name: "JK1 cell delta voltage"
    average_cell_voltage:
      name: "JK1 cell average voltage"
    cell_voltage_1:
      name: "JK1 cell voltage 1"
    cell_voltage_2:
      name: "JK1 cell voltage 2"
    cell_voltage_3:
      name: "JK1 cell voltage 3"
    cell_voltage_4:
      name: "JK1 cell voltage 4"
    cell_voltage_5:
      name: "JK1 cell voltage 5"
    cell_voltage_6:
      name: "JK1 cell voltage 6"
    cell_voltage_7:
      name: "JK1 cell voltage 7"
    cell_voltage_8:
      name: "JK1 cell voltage 8"
    cell_resistance_1:
      name: "JK1 cell resistance 1"
    cell_resistance_2:
      name: "JK1 cell resistance 2"
    cell_resistance_3:
      name: "JK1 cell resistance 3"
    cell_resistance_4:
      name: "JK1 cell resistance 4"
    cell_resistance_5:
      name: "JK1 cell resistance 5"
    cell_resistance_6:
      name: "JK1 cell resistance 6"
    cell_resistance_7:
      name: "JK1 cell resistance 7"
    cell_resistance_8:
      name: "JK1 cell resistance 8"
    total_charging_cycle_capacity:
      name: "JK1 total charging cycle capacity"

text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: jk_bms1
    errors:
      name: "JK1 Errors"

switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: jk_bms1
    charging:
      name: "JK1 Charging"
    discharging:
      name: "JK1 Discharging"
    balancer:
      name: "JK1 Balancing"

  - platform: ble_client
    ble_client_id: jk_ble1
    name: "JK1 enable bluetooth connection"
    id: ble_client_switch0
